dist: nue-todo
navigation:
  header:
    - Nue Tudo: /

  footer:
    - © Barton Hammond: /

    - image: /nue-todo/img/github.svg
      url: //github.com/bartonhammond/nue-todo
      alt: Github Projects
      size: 22 x 22
